### ISSUE TITLE
Some questions of paper

### ISSUE THREAD

**Issue by JiuqingDong** [wangsr126/NDet#1]
Dear author, I want to know what is the toy loss. I didn't understand Figure 6.

**Comment by JiuqingDong** [comment]
There is another question is that: in Equation 2, why bk equals to bk-1?
<img width="165" alt="image" src="https://user-images.githubusercontent.com/111500217/201510056-9a837117-5acd-42bf-a644-08eb5476f1ec.png">

**Comment by wangsr126** [comment]
The detectors shown in Fig. 6 are trained with parameters updated by the gradients from losses calculated by the predictions and noisy annotations. The toy losses are calculated by the predictions and clean annotations during the training but are not used to update the parameters. They are used as monitors to evaluate whether the detectors are over-fitted to noisy annotations. If over-fitting happens, the predictions will lean toward noisy annotations and away from clean annotations, which present with decreasing original losses and increasing toy losses. Well, it apparently not happens according to Fig. 6.

**Comment by wangsr126** [comment]
We assume it is a static system, which makes sense since the bounding box will not move itself at each measurement. Thus, bk=b-k1

**Comment by JiuqingDong** [comment]
Thank you for your answers. Well, I believe it is a really good job. The discussion gives me some inspiration, especially the part about the teacher-student learning strategy. I already did some experiments, and it works. 
By the way, I didn't find relevant codes for visualizing the noise distribution (Figure 3,5,10 in your paper). Did you release them? Anyway,  it seems that these are not important. I can also write the code myself for visualization. Just a query.

**Comment by JiuqingDong** [comment]
Hi, How did you draw the relative error in Figure.3? I am confused about it. 
The variance is related to the size, which means that the variance is unfixed because the size is different. If the variance is not fixed, how to draw a Gaussian curve?

**Comment by JiuqingDong** [comment]
How to draw the scatter plot in Figure 3? The axis units are 4, 8, 16, 32, and 64.... How did you implement it?
